### ISSUE TITLE
Problem with path validation

### ISSUE THREAD

**Issue by philcart** [valmack/circleci-config-validator#1]
Despite passing the CircleCI command line config validation and the pipeline running successfully
![image](https://user-images.githubusercontent.com/4084083/103715447-c0d9cf80-5014-11eb-902f-777ef171b31c.png)

The extension still highlights schema problems
![image](https://user-images.githubusercontent.com/4084083/103715282-53c63a00-5014-11eb-8192-0ecc3732ebe6.png)

Is there something else that I should be using instead of a dot?

Cheers
Phil

**Comment by v-stickykeys** [comment]
Thanks for reporting Phil. Can you paste your full config? I can then try to debug this.

I'm guessing CircleCi's core validator is out of sync with their graphql one that this package uses.

**Comment by philcart** [comment]
Hi Val, while I'm not able to provide our full file, here is a cut down version that has the issue.

```
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0
  aws-s3: circleci/aws-s3@2.0.0
  win: circleci/windows@2.2.0 

jobs:
  build_and_package:
    executor: win/default
    parameters:
      function_name:
        type: string
        default: MyFunction
    
    steps:
       - checkout
       - run: dotnet tool install -g Amazon.Lambda.Tools
       - run: dotnet build
       - run: 
          command: dotnet lambda package -o ../Artifacts/<< parameters.function_name >>.zip
          working_directory: << parameters.function_name >>
       - store_artifacts: 
          path: Artifacts
       - persist_to_workspace:
          root: Artifacts
          paths: .
  upload_package:
    resource_class: small
    executor: aws-cli/default     
    parameters:
      function_name:
        type: string
        default: MyFunction
      bundle_bucket:
        type: string
        default: my-release-bucket
        description: The s3 bucket where an application revision will be stored
    steps:
      - attach_workspace:
          at: Artifacts
      - aws-s3/copy:
          from: Artifacts/<< parameters.function_name >>.zip
          to: 's3://<< parameters.bundle_bucket >>'
      - run:
          name: update_function_code
          command: |
            aws lambda update-function-code \
              --function-name << parameters.function_name >> \
              --s3-bucket << parameters.bundle_bucket >> \
              --s3-key << parameters.function_name >>.zip
      - persist_to_workspace:
          root: Artifacts
          paths: .
workflows:
  build_and_upload:
    jobs:
      - build_and_package:
          name: build_default
      - upload_package:
          requires:
            - build_default
```
